### PR TITLE
Avoid fallback routine buffer overruns

### LINKED ISSUE #45: Double precision from_chars parsing incorrectly on reused buffer
Examples from the benchmark PR (test_boost_to_chars with chars_format::general):

```
Roundtrip failure with: -1042963531082612
          to_chars val: -1042963531082612.5
          to_chars ptr: 19
        from_chars val: -1.042963531082612e+164
        from_chars ptr: 24
Roundtrip failure with: -2984127144195026
          to_chars val: -2984127144195026.5
          to_chars ptr: 19
        from_chars val: -2.984127144195027e-233
        from_chars ptr: 24
Roundtrip failure with: 1816265025891540
          to_chars val: 1816265025891539.5
          to_chars ptr: 18
        from_chars val: 1.81626502589154e-98
        from_chars ptr: 24
Roundtrip failure with: 217945471321669.8
          to_chars val: 217945471321669.75
          to_chars ptr: 18
        from_chars val: 0
        from_chars ptr: 24
```

Single precision does not have any issues.

### PR DESCRIPTION
**Pull request by mborland**
Closes: #45 

`std::strtod` does not accept a size argument so when parsing a buffer with valid contents past `last` the results would be incorrect. Locally ran the benchmarks from #44 that caused the linked issue, and they are resolved.

### CODE REVIEW

**Comment by mborland** [comment]
@pdimov I bumped up the statically allocated array size form 256 to 1024, and added handling for a dynamic array using `malloc`. I also removed all of the default initializations like you asked. Let me know if you find anything else.

File: include/boost/charconv/from_chars.hpp [hunk 1]
```diff
@@ -94,35 +95,36 @@ BOOST_CHARCONV_GCC5_CONSTEXPR from_chars_result from_chars(const char* first, co
...
-from_chars_result from_chars_strtod(const char* first, const char* last, T& value) noexcept
+from_chars_result from_chars_strtod_impl(const char* first, const char* last, T& value, char* buffer) noexcept
 {
     // For strto(f/d)
     // Floating point value corresponding to the contents of str on success.
     // If the converted value falls out of range of corresponding return type, range error occurs and HUGE_VAL, HUGE_VALF or HUGE_VALL is returned.
     // If no conversion can be performed, 0 is returned and *str_end is set to str.
 
-    value = 0;
+    std::memcpy(buffer, first, static_cast<std::size_t>(last - first));
```
Comment (pdimov) [inline include/boost/charconv/from_chars.hpp:105]: You should add a trailing zero here.

File: include/boost/charconv/from_chars.hpp [hunk 2]
```diff
@@ -136,7 +138,31 @@ from_chars_result from_chars_strtod(const char* first, const char* last, T& valu
...
-    return {str_end, std::errc()};
+    return {first + (str_end - buffer), std::errc()};
+}
+
+template <typename T>
+inline from_chars_result from_chars_strtod(const char* first, const char* last, T& value) noexcept
+{
+    if (last - first < 1024)
+    {
+        char buffer[1024] {};
```
Comment (pdimov) [inline include/boost/charconv/from_chars.hpp]: ... which would allow you to remove the initialization here...

File: include/boost/charconv/from_chars.hpp [hunk 3]
```diff
@@ -136,7 +138,31 @@ from_chars_result from_chars_strtod(const char* first, const char* last, T& valu
...
+        return from_chars_strtod_impl(first, last, value, buffer);
+    }
+
+    // If the string to be parsed does not fit into the 1024 byte static buffer than we have to allocate a buffer.
+    // malloc is used here because it does not throw on allocation failure.
+
+    char* buffer = static_cast<char*>(std::malloc(last - first + 1));
```
Comment (pdimov) [inline include/boost/charconv/from_chars.hpp:157]: ... because you're not initializing `buffer` here anyway.

**Comment by pdimov** [comment]
You should merge/rebase the `develop` branch here to pick up my new test.

**Comment by mborland** [comment]
> You should merge/rebase the `develop` branch here to pick up my new test.

The force push was a rebase onto develop so I have it, and there are no new failures.
